language: node_js
node_js:
  - "node"
  - "16"


before_script:
  - npm install


script:
  - npm test
services: mongodb
# after_success:
#   - npm run report-coveralls
#   - npm run report-codecov